#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.

def total_sum(arr, row, col):
    sum1 = 0
    sum1 = sum1 + arr[row-1][col-1] + arr[row-1][col] + arr[row-1][col+1]
    sum1 += arr[row][col]
    sum1 += arr[row+1][col-1] + arr[row+1][col] + arr[row+1][col+1]
    return sum1

def hourglassSum(arr):
    max_sum = -63
    for i in range(1,5):
        for j in range(1,5):
            curr_sum = total_sum(arr, i, j)
            if curr_sum > max_sum:
                max_sum = curr_sum
    return max_sum
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
